# Generated by Django 3.1.6 on 2021-05-31 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0003_auto_20210531_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='day',
            field=models.CharField(choices=[('MONDAY', 1), ('TUESDAY', 2), ('WEDNESDAY', 3), ('THURSDAY', 4), ('FRIDAY', 5), ('SATURDAY', 6), ('SUNDAY', 7)], max_length=10),
        ),
    ]
