# Generated by Django 3.1.6 on 2021-05-31 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0007_auto_20210531_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='day',
            field=models.CharField(choices=[('Monday', 'A'), ('Tuesday', 'B'), ('Wednesday', 'C'), ('Thursday', 'D'), ('Friday', 'E'), ('Saturday', 'F'), ('Sunday', 'G')], max_length=10),
        ),
    ]
