# Generated by Django 3.1.6 on 2021-05-31 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0008_auto_20210531_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='day',
            field=models.CharField(choices=[('Monday', 'M'), ('Tuesday', 'TU'), ('Wednesday', 'W'), ('Thursday', 'TH'), ('Friday', 'FR'), ('Saturday', 'SA'), ('Sunday', 'SU')], max_length=10),
        ),
    ]
