# Generated by Django 3.1.6 on 2021-05-31 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0003_auto_20210531_0830'),
        ('accounts', '0003_remove_account_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_cr',
            field=models.BooleanField(default=False, verbose_name='Is CR'),
        ),
        migrations.AddField(
            model_name='account',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='students', to='sections.section'),
        ),
    ]
