# Generated by Django 3.1.6 on 2021-05-30 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sections', '0002_auto_20210529_1422'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable', to='sections.section')),
            ],
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=30)),
                ('starts_at', models.TimeField()),
                ('ends_at', models.TimeField()),
                ('venue', models.CharField(blank=True, max_length=30, null=True)),
                ('day', models.PositiveSmallIntegerField(choices=[(1, 'MONDAY'), (2, 'TUESDAY'), (3, 'WEDNESDAY'), (4, 'THURSDAY'), (5, 'FRIDAY'), (6, 'SATURDAY'), (7, 'SUNDAY')])),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetables.timetable')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('venue', models.CharField(max_length=30)),
                ('desc', models.CharField(blank=True, max_length=100, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetables.timetable')),
            ],
        ),
    ]
