# Generated by Django 3.1.6 on 2021-05-30 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetables', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='timetables.timetable'),
        ),
        migrations.AlterField(
            model_name='period',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='timetables.timetable'),
        ),
    ]
